private async aggregateTokenMetrics(asset: Asset): Promise<TokenMetrics> {
  // ...
  return {
    // ...
    timestamp: new Date().toISOString(), // Convert Date to string
    // ...
  };
}

private async aggregateNFTMetrics(asset: Asset): Promise<NFTMetrics> {
  // ...
  return {
    // ...
    timestamp: new Date().toISOString(), // Convert Date to string
    // ...
  };
} 