export const TOKEN_ADDRESSES = {
  WIF: 'HFX1SvzjctqHgA3MdPKiJJ4UG1UhYsGUCqVe6TF2kPWL',
  POPCAT: '5zqtEQpwRXqLtoQGADRoUbTxTLYuJNwR3obFhxkP6rbz',
  PNUT: '6QBFX7KvyfQAFxqG4YNuHLs8GQHR3cpoc1VLGMXtYGPZ',
  MEW: '4GZE3qZGYsdAAUnf3qn7kKQfQYQEEVjw1xqNwB4GQZH6',
  GOAT: '8CzsSyYQR4rcQGLDYGVZ4TgYKVwXxW5K8sMKaQf2YvGq',
  MOODENG: 'MooNPwuNcQYWHxKD3GJGHvhY3vLmX8MpJvJkKJm8Kf6',
  CHILLGUY: 'CHiLLGUYxx7zsXWfnuBQ8YKKHxJZCn2AGRVxvpQZKvn4',
  BRETT: 'BRETTnEb4o1s4cqvZ7j1AZHzqGCUTvaqP3KCLDzdCPf7'
} as const

export type TokenSymbol = keyof typeof TOKEN_ADDRESSES 