create table funding_arbitrage_opportunities (
    id bigint generated by default as identity primary key,
    coin text not null,
    strategy text not null,
    hyperliquid_rate numeric not null,
    counterparty text not null,
    counterparty_rate numeric not null,
    spread numeric not null,
    annualized_yield numeric not null,
    position text not null,
    timestamp timestamp with time zone not null,
    created_at timestamp with time zone default now(),
    
    -- Create unique constraint to prevent duplicates
    unique(coin, strategy, counterparty)
);

-- Create indices for faster queries
create index idx_funding_arb_spread on funding_arbitrage_opportunities(spread);
create index idx_funding_arb_yield on funding_arbitrage_opportunities(annualized_yield);
create index idx_funding_arb_timestamp on funding_arbitrage_opportunities(timestamp);
create index idx_funding_arb_position on funding_arbitrage_opportunities(position);
create index idx_funding_arb_strategy on funding_arbitrage_opportunities(strategy);

-- Add RLS policies
alter table funding_arbitrage_opportunities enable row level security;

-- Allow authenticated users to read
create policy "Allow authenticated users to read funding opportunities"
on funding_arbitrage_opportunities
for select
to authenticated
using (true);  